server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: true

user-eureka-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/temp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    name: root
    password: ZhangTao521#
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: user-consumer-ribbon



