spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: ZhangTao521#
    driver-class-name: com.mysql.cj.jdbc.Driver



  mybatis:
    typeAliasespackage: com.example

    mapperLocations:
      classpath: mapper/*.xml


  redis:
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-wait: 1ms
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 10000ms





#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate :
#      dialect : org.hibernate.dialect.MySQL5Dialect
