server:
  port: 9001

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/temp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: ZhangTao521#
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 0


logging:
  level:
    com:
      example:
        rediscache:
          mapper:

